name: ci-linux
on:
  pull_request:
  push:
    paths:
      - '.github/workflows/ci-linux.yaml'
      - 'cabal.project'
      - '*/src/**'

# INFO: The following configuration block ensures that only one build runs per branch,
# which may be desirable for projects with a costly build process.
# Remove this block from the CI workflow to let each CI job run to completion.
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup haskell and with cached dependencies
        uses: ./.github/actions/haskell-setup-cached
        with:
          fail-on-cache-miss: false

  build-all:
    needs: build
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
      - name: Setup haskell and with cached dependencies
        uses: ./.github/actions/haskell-setup-cached
      - name: Build all
        run: cabal build -j all
        
  build-documentation:
    needs: build
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
      - name: Setup haskell and with cached dependencies
        uses: ./.github/actions/haskell-setup-cached
      - name: Build documentation
        run: cabal haddock -j all
        

  test-all:
    needs: build
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
      - name: Setup haskell and with cached dependencies
        uses: ./.github/actions/haskell-setup-cached
      - name: Install integration test dependencies
        run: |
          cabal install -j cardano-node cardano-cli --overwrite-policy=always
          cabal install -j convex-wallet --overwrite-policy=always
      - name: Test all
        run: cabal test all
